language: java
jdk:
# JDK6 isn't supported after Jersey upgrade 2.6 -> 2.21
#  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - mvn clean verify
  - java -jar NetLicensingClient-demo/target/netlicensing-client-demo.jar
after_success:
  - test "${TRAVIS_JDK_VERSION}" == "openjdk7" && test "${TRAVIS_TEST_RESULT}" == "0" && mvn deploy -Drepo.snapshots.url=https://oss.sonatype.org/content/repositories/snapshots
